<a href="https://colab.research.google.com/github/caevalareti/linear-equation/blob/master/linear_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# declaring matrix
A = np.array([[1,1],[-3,1]])
B = np.array([[6],[2]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# finding X
X = np.dot(A_inverse, B)

In [13]:
A

array([[ 1,  1],
       [-3,  1]])

In [14]:
B

array([[6],
       [2]])

In [15]:
A_inverse

array([[ 0.25, -0.25],
       [ 0.75,  0.25]])

In [0]:
X = np.linalg.solve(A,B)

In [18]:
X

array([[1.],
       [5.]])

In [38]:
# Or, you can type your own values
import numpy as np
import sys

print("First array: ")

a1 = int(input("No. of rows: "))
b1 = int(input("No. of columns: "))

print("Second array")

a2 = int(input("No. of rows: "))
b2 = int(input("No. of columns: "))

if b1 != a2:
    print("Wrong array size!")
    sys.exit(-1)

array1 = np.zeros((a1,b1))
array2 = np.zeros((a2,b2))

print("Enter first array:")
for x in range(0,a1):
    for y in range(0,b1):
        array1[x,y] = float(input("Enter %d %d: " % (x,y)))

print(array1)

print("Enter second array:")    
for x in range(0,a2):
    for y in range(0,b2):
        array2[x,y] = float(input("Enter %d %d: " % (x,y)))

print(array2)

# find the inverse of A
array1_inverse = np.linalg.inv(array1)

# finding X
X = np.dot(array1_inverse, array2)

print('Inverse of A:', array1_inverse)
print('Matrix X:', X)

First array: 
No. of rows: 2
No. of columns: 2
Second array
No. of rows: 2
No. of columns: 1
Enter first array:
Enter 0 0: 1
Enter 0 1: 1
Enter 1 0: -3
Enter 1 1: 1
[[ 1.  1.]
 [-3.  1.]]
Enter second array:
Enter 0 0: 6
Enter 1 0: 2
[[6.]
 [2.]]
Inverse of A: [[ 0.25 -0.25]
 [ 0.75  0.25]]
Matrix X: [[1.]
 [5.]]
