<a href="https://colab.research.google.com/github/caevalareti/linear-equation/blob/master/linear_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# declaring matrix
A = np.array([[1,1],[-3,1]])
B = np.array([[6],[2]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# finding X
X = np.dot(A_inverse, B)

In [40]:
A

array([[ 1,  1],
       [-3,  1]])

In [41]:
B

array([[6],
       [2]])

In [42]:
A_inverse

array([[ 0.25, -0.25],
       [ 0.75,  0.25]])

In [43]:
X

array([[1.],
       [5.]])